### ISSUE TITLE
[lecture_comparison] Check instances of code not being compiled

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-advanced.myst#15]
This is an issue that a code is not compiled.

Here is an example:
Left:```RST Right:```MyST```
![Screen Shot 2021-01-22 at 5 44 43 pm](https://user-images.githubusercontent.com/44494439/105456707-bb99a780-5cd9-11eb-9795-b7c103cc6b91.png)
 
This occurs in:
[16](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/matsuyama.html)
[32](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/lucas_model.html)
[33](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/black_litterman.html)
[35](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/bcg_incomplete_mkts)
[39](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/amss.html)
[40](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/amss2.html)
[41](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/amss3.html)
[42](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/chang_ramsey.html)
[43](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/chang_credible.html)

cc: @mmcky

**Comment by sayaikegawa** [comment]
After fixing this issue, ```Value Error``` and ```Name Error``` in lecture No. 39, 42 and 43 should be checked because those errors which happens in 41's ```RST``` do not occur  in the ```MyST``` output.

**Comment by mmcky** [comment]
Trialling c67b37d in PR #4

**Comment by mmcky** [comment]
I suspect many of these are due to no code from files which is now up and running in PR #4 

For example, it looks like `lucas_model` is running and executing the code. 

@shlff would you be able to run through the links above and check against the latest build in PR #4 which includes the code from files?

**Comment by shlff** [comment]
Thanks @mmcky and @sayaikegawa . 

Hi @mmcky , I checked the corresponding code and output in the latest build in PR #4 (https://607d30a416bfbb1ec11723fc--wonderful-lalande-528d1c.netlify.app/intro.html) and I find the issue still exists in:
- [16](https://607d30a416bfbb1ec11723fc--wonderful-lalande-528d1c.netlify.app/matsuyama.html)
- [32](https://607d30a416bfbb1ec11723fc--wonderful-lalande-528d1c.netlify.app/knowing_forecasts_of_others.html)
- [39](https://607d30a416bfbb1ec11723fc--wonderful-lalande-528d1c.netlify.app/opt_tax_recur.html)
- [40](https://607d30a416bfbb1ec11723fc--wonderful-lalande-528d1c.netlify.app/amss.html)
- [41](https://607d30a416bfbb1ec11723fc--wonderful-lalande-528d1c.netlify.app/amss2.html)
- [42](https://607d30a416bfbb1ec11723fc--wonderful-lalande-528d1c.netlify.app/amss3.html)
- [43](https://607d30a416bfbb1ec11723fc--wonderful-lalande-528d1c.netlify.app/chang_ramsey.html)

**Comment by mmcky** [comment]
thanks @shlff -- if you have time can you dig into each of these lectures to try and figure out why they aren't executing. 

To get the same software environment you can use the `environment.yml` file to create a conda environment

```
conda env create -f environment.yml
conda activate quantecon
```

and then you can look in the `_build/jupyter_executed` to get some further details (or `_build/html/reports`)

**Comment by mmcky** [comment]
@shlff I know the reason -- I need to migrate `file` to `load`

**Comment by mmcky** [comment]
For `matsuyama` and `black_litterman` I have opened #28 as this is a widget issue.
