### ISSUE TITLE
[amss] Build Error

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced.myst#163]
@kp992 would you have time to look into the build error for amss

```
ValueError: V and W need to be successfully computed before simulation.
```

The build cache is failing so it is failing on the fresh build of the lectures. The diff (preview) built fine as amss didn't execute in that context.

**Comment by kp992** [comment]
Hmm, digging into this looks like there multiple bugs. Just running the latest version locally, I see:
```py
>>> amss_model.solve(V, σ_v_star, b_0, W, σ_w_star)
...
File ~/mambaforge/envs/qe/lib/python3.10/site-packages/interpolation/splines/eval_splines.py:100, in __eval_spline(grid, C, points, out, k, diff, extrap_mode)
     98 @overload(_eval_spline)
     99 def __eval_spline(grid, C, points, out=None, k=1, diff="None", extrap_mode="linear"):
--> 100     kk = (k).literal_value
    101     diffs = (diff).literal_value
    102     extrap_ = (extrap_mode).literal_value

AttributeError: 'Integer' object has no attribute 'literal_value'
```

**Comment by mmcky** [comment]
@kp992 this is blocking our ability to publish. Any ideas on how we can fix this.

**Comment by kp992** [comment]
@mmcky I am trying to figure out fix or some workarounds.

**Comment by kp992** [comment]
@mmcky If we need a quick release, one option is to just pin "numba<0.60". That will work fine. Till then, I am trying to fix the issue in numba 0.60.

**Comment by mmcky** [comment]
thanks @kp992 -- nice suggestion.

**Comment by kp992** [comment]
May be this is the issue:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
interpolation 2.2.6 requires numba>=0.59.1, but you have numba 0.59.0 which is incompatible.
```

So, pip resolver is picking numba=0.60 (which is the latest one)
