### ISSUE TITLE
Long Run Time on Lecture causing build cache issues

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced.myst#183]
@kp992 this lecture

https://python-advanced.quantecon.org/black_litterman.html

is taking a very long time to run. 

I suspect this is worse than in the past. 

Would you have time to review this lecture to see if we can compute it under 3000minutes?

**Comment by kp992** [comment]
Thanks for pointing that out @mmcky. I can have a look at it and try to optimize it.
