### ISSUE TITLE
[lecture review] \argmin and \col not compiled

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#49]
Hi @mmcky , ``\argmin`` is not compiled in the following lectures (updating):
- [1_orth_proj](https://quantecon.github.io/lecture-python-advanced.myst/orth_proj.html)

``\col`` is not compiled in the following lectures (updating):
- [1_orth_proj](https://quantecon.github.io/lecture-python-advanced.myst/orth_proj.html)

E.g., please find the issue of ``\argmin`` from the screenshots (left: RST, right: MYST):
![Screen Shot 2021-05-29 at 5 16 11 pm](https://user-images.githubusercontent.com/53931041/120275679-0a44f700-c2f5-11eb-90cc-60d7c27635d8.png)

![Screen Shot 2021-05-29 at 6 24 20 pm](https://user-images.githubusercontent.com/53931041/120275714-1761e600-c2f5-11eb-8ca8-23fd9e0882e9.png)

E.g., please find the issue of ``\argmin`` from the screenshots (left: RST, right: MYST):
![Screen Shot 2021-05-29 at 6 21 06 pm](https://user-images.githubusercontent.com/53931041/120275866-48421b00-c2f5-11eb-826d-d45441552902.png)
![Screen Shot 2021-05-29 at 6 24 57 pm](https://user-images.githubusercontent.com/53931041/120275883-4d06cf00-c2f5-11eb-8a91-df897ab3c204.png)

**Comment by mmcky** [comment]
The `_config.yml` setting for `TeX` macros doesn't seem to be taking effect

**Comment by mmcky** [comment]
@AakashGfude is there a way to specify TeX macros in the theme config? Doesn't look like the `sphinx` settings are passing through to mathjax now.

**Comment by AakashGfude** [comment]
@mmcky @shlff the `\argmin` should be working in the live site. not sure what `\col` is. Can someone post a link to a document describing what`\col` command is and I can see how to handle it?

**Comment by mmcky** [comment]
@AakashGfude we used to have this for the old site

https://github.com/QuantEcon/lecture-python/blob/5f8bee9be8fa5e2089186fb5eb142f75056bbfb8/theme/minimal/templates/latex.tpl#L84

So looks like we just need `\col` -> `col`

**Comment by mmcky** [comment]
Actually this looks like what we need for the Macros

https://github.com/QuantEcon/lecture-python/blob/5f8bee9be8fa5e2089186fb5eb142f75056bbfb8/theme/minimal/static/js/base.js

**Comment by AakashGfude** [comment]
awesome. thanks @mmcky
