### ISSUE TITLE
[lecture enhancement] write links implicitly

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#51]
Hi @mmcky and @jstac , I find there are some links to external websites written explicitly.

Do you think it would be better to write the link implicitly, like [this reference](https://en.wikipedia.org/wiki/Linear_map#Matrices)? If so then I would create a PR to improve it.

e.g., in lecture [orth_proj](https://quantecon.github.io/lecture-python-advanced.myst/orth_proj.html#projection-via-matrix-algebra) (left: RST; right: MYST):
![Screen Shot 2021-05-29 at 6 01 59 pm](https://user-images.githubusercontent.com/53931041/120716965-22419400-c50a-11eb-9295-412260075dcf.png)

and this 

![Screen Shot 2021-06-01 at 5 07 24 pm](https://user-images.githubusercontent.com/53931041/120717385-c9263000-c50a-11eb-9489-c1b981a26426.png)

**Comment by mmcky** [comment]
@shlff I think this is a good idea -- please go ahead with a PR.
