### ISSUE TITLE
[lecture review] inserted figures uncentered

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#52]
Hi @mmcky , I find that inserted figures are not centered.

e.g., (left: RST; right: MYST):
![Screen Shot 2021-05-29 at 8 00 35 pm](https://user-images.githubusercontent.com/53931041/120717282-9f6d0900-c50a-11eb-9771-ebfee21f2815.png)

![Screen Shot 2021-06-03 at 11 25 01 am](https://user-images.githubusercontent.com/53931041/120726655-f0d1c400-c51b-11eb-9fe0-430024be214c.png)

![Screen Shot 2021-06-03 at 11 25 28 am](https://user-images.githubusercontent.com/53931041/120726669-fc24ef80-c51b-11eb-84fc-677b7e0e45e7.png)

**Comment by mmcky** [comment]
@shlff this should be doable by updating the `md`

```
:align: center
```

for `figure` directives
