### ISSUE TITLE
[lecture review] code cells compiled but the plots generated unshown

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#54]
Hi @mmcky , I find that there are some code cells compiled but the plots generated unshown in the following lectures (updating):
- [lu_tricks](https://quantecon.github.io/lecture-python-advanced.myst/lu_tricks.html)

e.g., (left: RST; right: MYST):
![Screen Shot 2021-06-03 at 1 57 15 pm](https://user-images.githubusercontent.com/53931041/120718141-28387480-c50c-11eb-9b61-e171117fb5c9.png)

**Comment by AakashGfude** [comment]
@shlff the images seem to be loading in my machine. can you check again? maybe it was a slow internet issue?

**Comment by shlff** [comment]
Thanks @AakashGfude . I re-checked it again and it is working now. 

I will close this issue.
