### ISSUE TITLE
[lecture review] Italic and bold in titles

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#56]
Hi @mmcky , I find when there are some italic parts in titles, they don't look very consistent with our new bold style titles.

e.g., in [lecture](https://quantecon.github.io/lecture-python-advanced.myst/black_litterman.html#adding-views) (left: RST; right: MYST):

![Screen Shot 2021-06-03 at 2 54 09 pm](https://user-images.githubusercontent.com/53931041/120718667-012e7280-c50d-11eb-89f4-d38a8d284b68.png)

**Comment by mmcky** [comment]
This is true. I will tag this as a theme improvement.
