### ISSUE TITLE
[lecture review] uncompiled code cells

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#57]
Hi @mmcky , I find there are some uncompiled code cells in lectures (updating):
- [black_litterman](https://quantecon.github.io/lecture-python-advanced.myst/black_litterman.html#adding-views)
- [chang_ramsey](https://quantecon.github.io/lecture-python-advanced.myst/chang_ramsey.html)
- [matsuyama](https://quantecon.github.io/lecture-python-advanced.myst/matsuyama.html)

e.g., (left: RST; right: MYST):

![Screen Shot 2021-06-03 at 3 00 12 pm](https://user-images.githubusercontent.com/53931041/120719499-bbbe7500-c50d-11eb-9b74-ead6614b50a5.png)

![Screen Shot 2021-06-03 at 3 00 59 pm](https://user-images.githubusercontent.com/53931041/120719510-bfea9280-c50d-11eb-9fc4-904caae4d38e.png)

![Screen Shot 2021-06-03 at 3 01 27 pm](https://user-images.githubusercontent.com/53931041/120719522-c2e58300-c50d-11eb-9073-0b34cf0a9be6.png)

![Screen Shot 2021-06-03 at 4 28 17 pm](https://user-images.githubusercontent.com/53931041/120726445-6d17d780-c51b-11eb-8e29-b9ccef132f12.png)

![Screen Shot 2021-06-03 at 4 28 45 pm](https://user-images.githubusercontent.com/53931041/120726457-73a64f00-c51b-11eb-8c02-b0511ae8b312.png)

![Screen Shot 2021-06-03 at 4 29 33 pm](https://user-images.githubusercontent.com/53931041/120726475-7c972080-c51b-11eb-9e24-ac162dfcbd95.png)

![Screen Shot 2021-06-03 at 4 29 59 pm](https://user-images.githubusercontent.com/53931041/120726499-8c166980-c51b-11eb-9fd2-2cd90ac4608c.png)

![Screen Shot 2021-06-03 at 11 23 38 am](https://user-images.githubusercontent.com/53931041/120726633-e1eb1180-c51b-11eb-8797-aae7c0ed3f9b.png)

**Comment by mmcky** [comment]
Thanks @shlff 

- [x] change_ramsey as expected

but the missing content in the others is a problem.

**Comment by mmcky** [comment]
@shlff if you run those lectures in `binder` do you see outputs or not (for those code-cells)?

**Comment by shlff** [comment]
Hi @mmcky , we can see outputs from those code-cells if we run them in ``binder``.

But I find that we need to install python packages before we import them.

**Comment by mmcky** [comment]
@shlff do you know which packages need to be installed? We should add those to the imports at the top of the lectures

**Comment by mmcky** [comment]
@AakashGfude do you know why this interact object isn't showing up

https://quantecon.github.io/lecture-python-advanced.myst/black_litterman.html#bayes-interpretation-of-the-black-litterman-recommendation

**Comment by mmcky** [comment]
Closing this issue as the main issue here is that `ipywidgets` aren't working in the theme #82
