### ISSUE TITLE
[lecture enhancement] uncentered equations

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#58]
Hi @jstac and @mmcky , I find there are some equations uncentered, which might be easier to read if we centralise them in lectures (updating):
- [BCG_incomplete_mkts](https://quantecon.github.io/lecture-python-advanced.myst/BCG_incomplete_mkts.html#pseudo-code)

Do you think it would be better to make these equations centred in these cases? If so, then I would create a PR for this.

e.g., (left: RST; right: MYST):
![Screen Shot 2021-06-03 at 3 13 46 pm](https://user-images.githubusercontent.com/53931041/120719855-59b23f80-c50e-11eb-91ac-648a30ea7d39.png)

**Comment by mmcky** [comment]
@shlff I think the `myst` version looks neater then the current version so I am happy with this as it is.
