### ISSUE TITLE
[lecture enhancement] some equation numbers are not internal reference so not updated

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#60]
Hi @mmcky , I find that there are some equation numbers are not internal reference so not updated in the following lectures:
- [amss2](https://quantecon.github.io/lecture-python-advanced.myst/amss2.html#rate-of-convergence)

Do you think it would be a good idea to make them internal referenced? If so then I would creat a PR for it.

e.g., (left: RST; right: MYST):

![Screen Shot 2021-06-03 at 4 08 29 pm](https://user-images.githubusercontent.com/53931041/120721484-43f24980-c511-11eb-8f7d-db7494d4a0a3.png)

**Comment by mmcky** [comment]
@shlff that is a problem. Good find.

The sources is:

```
(See the equation above equation (47) in {cite}`BEGS1`)
```

so it should be setup as an internal `{eq}` reference. Do you know which equation this refers to?

A PR would be great.

**Comment by shlff** [comment]
Hi @mmcky , I just found that this equation is not in our lecture but in the reference.

I will close this issue.
