### ISSUE TITLE
[lecture review] \colorblue not compiled

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#61]
Hi @mmcky I inspect that the latex code ``\color{blue}`` in the following lecture is not working:
- [hs_recursive_models](https://quantecon.github.io/lecture-python-advanced.myst/hs_recursive_models.html)

e.g., (left: RST; right: MYST):
![Screen Shot 2021-06-03 at 11 47 15 am](https://user-images.githubusercontent.com/53931041/120729472-9425d780-c522-11eb-94a2-7cb2c17cac8a.png)

**Comment by AakashGfude** [comment]
Thanks @shlff , I will have a look at this one.

**Comment by AakashGfude** [comment]
@shlff seems to be working in the link provided by you in the description https://quantecon.github.io/lecture-python-advanced.myst/hs_recursive_models.html#dynamic-demand-curves-and-canonical-household-technologies . Let me know if it still is an issue.

**Comment by shlff** [comment]
Thanks @AakashGfude . I tested it with Google Chrome. I also tested it with Safari and Google Chrome incognito, which look fine somehow.

**Comment by AakashGfude** [comment]
If you are happy with the present state, then we can close the issue.

**Comment by shlff** [comment]
Thanks @AakashGfude . I think it would be fine to close this issue.
