### ISSUE TITLE
[lecture enhancement] oversized inserted figures

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#62]
Hi @mmcky , I find that there are some oversized inserted figures. 

Do you think it would be a good idea to adjust their size manually like what we did before? If so, then I would investigate all possibly-oversized inserted figures and create a PR to adjust their sizes.

e.g., (left: RST; right: MYST):
![Screen Shot 2021-06-03 at 11 22 55 am](https://user-images.githubusercontent.com/53931041/120729727-3a71dd00-c523-11eb-9774-f0faf0c3f986.png)

![Screen Shot 2021-06-03 at 11 22 41 am](https://user-images.githubusercontent.com/53931041/120729786-61301380-c523-11eb-83e9-da7baee5e326.png)

**Comment by mmcky** [comment]
@shlff agree. Would you mind to adjust those figure sizes in PR's?
