### ISSUE TITLE
[lecture enhancement] some error messages in ``Chang`` lecture series

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#63]
Hi @jstac and @mmcky , I find that there are some error messages in lecture chang_ramsey([MYST](https://quantecon.github.io/lecture-python-advanced.myst/chang_ramsey.html)-version's code cells are not compiled, but we can see those error messages in [RST](https://python-advanced.quantecon.org/chang_ramsey.html)-version). Also in [chang_credible](https://quantecon.github.io/lecture-python-advanced.myst/chang_credible.html).

Do you think it would be a good idea to get rid of these errors? If so then I would try my best to figure out the issue and create a PR for this.

e.g., (left: RST; right: MYST):

![Screen Shot 2021-06-03 at 4 28 17 pm](https://user-images.githubusercontent.com/53931041/120730344-9d17a880-c524-11eb-825c-d0a59c1fc856.png)

![Screen Shot 2021-06-03 at 4 29 33 pm](https://user-images.githubusercontent.com/53931041/120730356-a43eb680-c524-11eb-8cd6-9014dc048db7.png)

![Screen Shot 2021-06-03 at 4 29 59 pm](https://user-images.githubusercontent.com/53931041/120730367-aa349780-c524-11eb-8bce-4776a090ffbe.png)

**Comment by mmcky** [comment]
thanks @shlff if a lecture doesn't execute correctly in `jupyter-cache` then the `jupyter-book` version doesn't show any outputs. So this is expected. 

These lectures are failing on the old site as well.
