### ISSUE TITLE
[lecture enhancement] code cell collapse/fold

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#64]
Hi @mmcky and @jstac , I find that we have a very good feature to collapse/fold a long-line code cell in our RST-version lectures. 

Do you think it is a good idea to translate this feature to the new MYST lectures as well?

e.g., in lecture [amss](https://quantecon.github.io/lecture-python-advanced.myst/amss.html) (left: RST; right: MYST):
![Screen Shot 2021-06-03 at 3 50 38 pm](https://user-images.githubusercontent.com/53931041/120730715-7017c580-c525-11eb-8008-4381a430d9cf.png)

**Comment by mmcky** [comment]
@shlff thanks.

This is now supported in the theme using `collapse-20` tag for `code-cells`

https://github.com/QuantEcon/quantecon-book-theme/pull/128

Would you mind raising pull request to update each lecture where the `collapse` was previously used?

**Comment by mmcky** [comment]
@AakashGfude for `collapse` can you just specify `collapse` for the default `20` lines or do you have to use `collapse-*`.

@shlff let's use `collapse-20` to be explicit.
