### ISSUE TITLE
[lecture enhancement] some outputs occupy too many spaces

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#65]
Hi @mmcky and @jstac , I find that there are some outputs of code cells that occupy too many lines and spaces in the following lectures:
- [amss](https://quantecon.github.io/lecture-python-advanced.myst/amss.html#anticipated-one-period-war)

Do you think it would be a good idea to find an elegant way to compress the output? I came up with three ideas that we can either 
- fold the output like what we did for long code cells in the RST-version lectures or like what we did for outputs of ``!pip install --upgrade`` in every lecture or
- we can put those outputs just in one output cell or
- we modify the code a bit to just print some of the results.

e.g., this output list is very long and I just show the very first part (left: RST; right: MYST):
![Screen Shot 2021-06-03 at 4 01 23 pm](https://user-images.githubusercontent.com/53931041/120731312-b4579580-c526-11eb-880c-1326b5240031.png)

**Comment by mmcky** [comment]
@AakashGfude I think this is happening when the output is of type `stream` to `stdout`. It looks like that `code-cell` output is a series of individual text outputs.

**Comment by mmcky** [comment]
I have opened a test run for `sphinx-book-theme` to see how they have handled stream output types

https://github.com/QuantEcon/lecture-python-advanced.myst/pull/67

**Comment by mmcky** [comment]
@AakashGfude this is the same upstream so maybe it is something we should fix there. 

In the meantime @shlff I think we should use `output_scroll` tag

https://jupyterbook.org/reference/cheatsheet.html#tags

Can you submit PR's?
