### ISSUE TITLE
[lecture review] footnote in-text citation styles

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-advanced.myst#66]
Hi @jstac and @mmcky , I also find that the in-text citation styles of footnotes in ``MYST`` lectures look different from those in ``RST`` lectures before. 

e.g., please see [knowing_forecasts_of_others's footnote 1](https://quantecon.github.io/lecture-python-advanced.myst/knowing_forecasts_of_others.html#id13) (left: RST; right: MYST):
![Screen Shot 2021-06-08 at 11 32 31 am](https://user-images.githubusercontent.com/53931041/121108860-d36b6580-c84d-11eb-8764-45ce76390e84.png)

As discussed with @AakashGfude , we think it would be better to follow the styles in ``RST`` lectures--to put the in-text footnote citations in the superscript (as what we did in the picture on the left-hand side above).

Do you think it is a good idea? Looking forward to your comments.

**Comment by mmcky** [comment]
hey @shlff I think replicating the styles from `rst` would be great 👍

**Comment by mmcky** [comment]
there is actually currently an issue with rendering the footnotes

https://github.com/QuantEcon/quantecon-book-theme/issues/180

**Comment by jstac** [comment]
Hi @AakashGfude , could you please update us on this issue?

**Comment by AakashGfude** [comment]
Hi @jstac @mmcky , the build locally for me seems to be working fine.
<img width="1180" alt="Screen Shot 2022-10-07 at 11 54 15 am" src="https://user-images.githubusercontent.com/6542997/194443879-4a52de89-d9db-4f66-bcda-d1ada869e58c.png">
