### ISSUE TITLE
Fix support for IPyWidgets in theme

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced.myst#82]
The `ipywidget` objects are again not showing through `quantecon-book-theme`

- [ ] matsuyama
- [ ] black_litterman

**Comment by AakashGfude** [comment]
It's weird. There are working fine in the local build. In Github pages though, embed-amd script is not loaded for some reason. even though both have the same versions.

**Comment by mmcky** [comment]
That is strange. Hmm

**Comment by mmcky** [comment]
@AakashGfude this looks ok on the live site now. Has anything changed?

**Comment by mmcky** [comment]
I think this can be closed now
