### ISSUE TITLE
Use `np.full`

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/lecture-python-advanced.myst#90]
See QuantEcon/lecture-python.myst#165

**Comment by shlff** [comment]
Thanks @oyamad . 

Hi @oyamad and @jstac , next I will identify the pattern ``np.ones * alpha`` through all advanced lectures, list related lectures and create a PR to modify this pattern.

**Comment by oyamad** [comment]
There are a few more in some `.py` files:

* https://github.com/QuantEcon/lecture-python-advanced.myst/blob/main/lectures/_static/lecture_specific/amss2/log_utility.py
* https://github.com/QuantEcon/lecture-python-advanced.myst/blob/main/lectures/_static/lecture_specific/amss2/crra_utility.py
* https://github.com/QuantEcon/lecture-python-advanced.myst/blob/main/lectures/_static/lecture_specific/opt_tax_recur/sequential_allocation.py
* https://github.com/QuantEcon/lecture-python-advanced.myst/blob/main/lectures/_static/lecture_specific/amss2/sequential_allocation.py
* https://github.com/QuantEcon/lecture-python-advanced.myst/blob/main/lectures/_static/lecture_specific/opt_tax_recur/recursive_allocation.py
* https://github.com/QuantEcon/lecture-python-advanced.myst/blob/main/lectures/_static/lecture_specific/amss2/recursive_allocation.py
